#!/bin/bash
gps=$(exiftool "$1" | grep "GPS Position"| cut -d: -f2)
if [ -n "${gps}" ];
then
	#echo "${gps}"
	dd=$(echo "$gps" | awk '{printf("%f,%f", $1 + $3/60 + $4/3600, $6+$8/60+$9/3600)}')
	#echo "${dd}"
	address=$(wget -O- -q "http://maps.google.com/maps/api/geocode/xml?latlng=${dd}&sensor=false"|grep formatted_address|head -n1|cut -d\> -f2|cut -d\< -f1)
	echo "${dd};${address}"
fi
